import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Axios from 'axios'
export default function Home() {


  const handleSubmit = async (e) => {



    e.preventDefault();

   Axios.post(`https://api.camiondaba.ma/api/register`, {nom: "adnane", prenom:"rouhi", email:"test@gmail.com", phone: "+2126505342", password: "1234567890"}, {headers: {
       'Content-Type': 'application/json',
       'X-Requested-With': 'XMLHttpRequest'
   }, })
     .then( res =>{
       
 
               
               
               console.log(res)
           if(!res.error){
               // setResponse({sending: false, success:true, donneIncorecte: false});
               // router.push("/logged_in");
             
           }else {
               // setResponse({sending: false, success:false, donneIncorecte:true})
               if(res.validator){
 
               }else{
 
               }
           }
      }
       
       ).catch(error =>{ 
           console.log(error.response)
           // setResponse({sending: false, success:false, donneIncorecte:true})
       })
 
   // const authUser = await createUserWithEmailAndPassword(data.email, data.password)
   // // .then(authUser => {
   //   console.log("Success. The user is created in Firebase")
     
   // // })
   // console.log(data)
  
   // fetch(`${Config.BACKEND_URL}/register`,{
   //     method:"post",
   //     headers: {
   //         'Content-Type': 'application/json',
   //     },
   //     body:JSON.stringify(data)
   // })
   // .then( res =>{
       
 
               
               
   //             console.log(res)
   //         if(res.error === false){
   //             setResponse({sending: false, success:true, donneIncorecte: false});
   //             // router.push("/logged_in");
             
   //         }else {
   //             setResponse({sending: false, success:false, donneIncorecte:true})
   //             if(res.validator){
 
   //             }else{
 
   //             }
   //         }
   //    }
       
   //     ).catch(error =>{ 
   //         console.log(error.response)
   //         setResponse({sending: false, success:false, donneIncorecte:true})
   //     })
 
 
 
 
   
 }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

       <button onClick = {handleSubmit}> send  </button>
      </main>

     
    </div>
  )
}
